name: S3 Tables Integration Tests

on:
  pull_request_target:
    types: [labeled]
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test-s3-tables:
    name: S3 Tables Tests - PR / python ${{ matrix.python-version }}
    if: contains(github.event.pull_request.labels.*.name, 'enable-functional-tests')
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    
    env:
      DBT_AWS_ACCOUNT: ${{ secrets.DBT_AWS_ACCOUNT }}
      DBT_GLUE_ROLE_ARN: ${{ secrets.DBT_GLUE_ROLE_ARN }}
      DBT_GLUE_REGION: ${{ secrets.DBT_GLUE_REGION }}
      DBT_S3_LOCATION: ${{ secrets.DBT_S3_LOCATION }}
      DBT_S3_TABLES_BUCKET: ${{ secrets.DBT_S3_TABLES_BUCKET }}
      DBT_TEST_USER_1: dbt_test_s3_tables_${{ github.run_id }}
      DBT_GLUE_SESSION_ID: dbt-s3-tables-test-${{ github.run_id }}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
        pip install -e .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.DBT_GLUE_ROLE_ARN }}
        aws-region: ${{ secrets.DBT_GLUE_REGION }}
        audience: sts.amazonaws.com

    - name: Run S3 Tables Tests
      run: |
        python -m pytest tests/functional/adapter/s3_tables/ -v --tb=short
      timeout-minutes: 60

    - name: Cleanup test resources
      if: always()
      run: |
        # Cleanup any test resources if needed
        echo "Cleaning up S3 tables test resources..."
        # Add cleanup commands here if necessary
